### ISSUE TITLE
PCM DPC Italian COVID-19

### ISSUE THREAD

**Issue by tfoldi** [starschema/COVID-19-data#2]
Official Italian repository: https://github.com/pcm-dpc/COVID-19

**Comment by grglyb** [comment]
Diff should be the difference since yesterday in case the total case is a running sum. I do not know if this data is a daily snapshot or a running sum. But the goal is to have columns where we can see for instance in case of "Recovered" how many reported recoveries happened since yesterday. --> This notebook caclulates DIFFs as today's snapshot data minus yesterday's snapshot data for Hospitalized, Intensive Care, Total Hospitalized (sum of Hospitalized and Intensive Care), Home Isolation, Total Positive, Discharged Healed, Deceased, Total Cases and Tested. New Positive cases are not calculated here as they are provided as change since yesterday in the source data. In v2 corrected total cases vs active cases issue.
please call the workbook as PCM_DPS_COVID19 to know who is the data provider --> notebook renamed to PCM_DPS_COVID19
we move S3 upload to a different place (out from the notebook). --> S3 uplaod removed (changed to markup)
Please output PCM_DPS_COVID19.csv as output (same as the basename of the notebook) --> output file renamed (easily configurable in Parameters section)
