### ISSUE TITLE
KFF_US_STATE_MITIGATIONS table went blank

### ISSUE THREAD

**Issue by psarnow** [starschema/COVID-19-data#226]
We are utilizing the Snowflake datashare to query the KFF_US_STATE_MITIGATIONS table along with the JHU_COVID_19 table.
This morning, noticed that all of the values are now NULL in the KFF_US_STATE_MITIGATIONS table except, COUNTRY_REGION, and LAST_UPDATED_DATE

**Comment by psarnow** [comment]
KFF_US_STATE_MITIGATIONS table data is back for us in Snowflake! Curious if this was a Starchema issue or Snowflake datashare issue?

**Comment by chrisvoncsefalvay** [comment]
Hi @psarnow – glad to hear! Neither, actually – the data source (KFF) had some changes with the way their data is held, and as a safety measure, our automated QA blanked out the table instead of filling it with inconsistent data. This doesn't happen often, but when it does, we're happy to respond quite quickly. Thanks again for making us aware!

**Comment by rmcnaughton** [comment]
Hi, could this possibly happen again in the future? if so would you recommend doing a check to see if data is null before pulling in the share?  we had published it as is & wiped out all our data as we were doing a merge to see if data changed at the state level.

**Comment by chrisvoncsefalvay** [comment]
Hi @rmcnaughton – sorry to hear that. We're already performing some checks, and we are adding a new test suite that does exactly that. We're always striving to be better in delivering sound data to you and our many end-users, and I doubt this will occur again. Thank you once again for letting us know about this.
